name: 'Build'
on:
  push:
  workflow_dispatch:

jobs:
  
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            BUILD_CMD: pyinstaller collectmeteranalog.spec
            POST_BUILD_CMD: >+
              Compress-Archive -Path dist/* -Destination dist/collectmeteranalog-windows.zip
            OUT_FILE_NAME: collectmeteranalog-windows.zip
            ASSET_MIME:
              application/zip
          - os: ubuntu-latest
            BUILD_CMD: pyinstaller collectmeteranalog.spec
            POST_BUILD_CMD: >
              cd dist/ &&
              ls -Rls &&
              zip -r9 collectmeteranalog-linux.zip collectmeteranalog
            OUT_FILE_NAME: collectmeteranalog-linux.zip
            ASSET_MIME: application/zip
          - os: macos-latest
            BUILD_CMD: pyinstaller collectmeteranalog.spec
            POST_BUILD_CMD: >
              cd dist/ &&
              ls -Rls &&
              zip -r9 collectmeteranalog-macos.zip collectmeteranalog
            OUT_FILE_NAME: collectmeteranalog-macos.zip
            ASSET_MIME: application/zip

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Pre-Build for ${{ matrix.os }}
        if: ${{ matrix.PRE_BUILD_CMD != '' }}
        run: ${{ matrix.PRE_BUILD_CMD }}

      - name: Build with pyinstaller for ${{ matrix.os }}
        run: ${{ matrix.BUILD_CMD }}

      - name: Post-Build for ${{ matrix.os }}
        if: ${{ matrix.POST_BUILD_CMD != '' }}
        run: ${{ matrix.POST_BUILD_CMD }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: './dist/${{matrix.OUT_FILE_NAME}}'   

      - name: Upload created build on action
        uses: actions/upload-artifact@v4
        with:
          path: './dist/${{matrix.OUT_FILE_NAME}}'
          name: '${{runner.os}}-${{matrix.OUT_FILE_NAME}}'
 
